### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rekado** [ratschlab/MiTie#1]
There is no license declaration for any of the source files of MiTie as far as I could tell.  Under what license is the code available?

As it links with GLPK, I suspect it should be GPLv3+, but I'm not sure.  I would be happy if you could clarify this by adding license declarations to the sources.

**Comment by rekado** [comment]
I'd really like to package MiTie, but without a license declaration I cannot do this.  It would be great if you could clarify under what license MiTie is released.

**Comment by akahles** [comment]
Sorry for the delay - we have put MiTie under GPL.

**Comment by rekado** [comment]
Thank you for adding a license.  Am I right in the assumption that this is "GPL version 3, or later" or do you explicitly restrict it to version 3 only?

(While it may seem pedantic, having this upgrade clause greatly simplifies license compatibility with other GPL software: https://www.gnu.org/licenses/gpl-faq#VersionThreeOrLater)

**Comment by akahles** [comment]
Let me check back with the other authors. I'll clarify soon.

**Comment by akahles** [comment]
We changed the the license to GPL3 or later.

**Comment by rekado** [comment]
That's beautiful!  Thank you for addressing this issue!
